In [3]:
import pandas as pd

In [61]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'
url = f'{prefix}//yellow_tripdata_2021-01.csv.gz'

In [62]:
df = pd.read_csv(url)

/tmp/ipykernel_127032/4176769558.py:1: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [64]:
df['tpep_pickup_datetime']

0          2021-01-01 00:30:10
1          2021-01-01 00:51:20
2          2021-01-01 00:43:30
3          2021-01-01 00:15:48
4          2021-01-01 00:31:49
                  ...
1369760    2021-01-25 08:32:04
1369761    2021-01-25 08:34:00
1369762    2021-01-25 08:37:00
1369763    2021-01-25 08:28:00
1369764    2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: str

In [65]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [66]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [67]:
len(df)

1369765

In [68]:
!uv add sqlalchemy "psycopg[binary,pool]"

Resolved 119 packages in 0.92ms
Checked 12 packages in 0.17ms

In [69]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [70]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [71]:
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [72]:
df.to_sql(name='yellow_taxi_data', con=engine)

ValueError: Table 'yellow_taxi_data' already exists.

In [73]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [84]:
len(df)

100000

In [82]:
df = next(df_iter)

StopIteration:

In [83]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
400000,2,2021-01-13 09:20:26,2021-01-13 09:30:27,1,1.13,1,N,186,233,1,8.0,0.0,0.5,2.26,0.00,0.3,13.56,2.5
400001,2,2021-01-13 09:42:08,2021-01-13 09:46:46,1,0.71,1,N,161,170,1,5.0,0.0,0.5,1.24,0.00,0.3,9.54,2.5
400002,1,2021-01-13 09:40:08,2021-01-13 10:00:22,1,3.00,1,N,238,74,2,15.0,2.5,0.5,0.00,0.00,0.3,18.30,2.5
400003,2,2021-01-13 09:40:30,2021-01-13 09:49:22,1,1.00,1,N,140,162,1,7.0,0.0,0.5,2.58,0.00,0.3,12.88,2.5
400004,2,2021-01-13 09:43:05,2021-01-13 09:48:14,1,0.94,1,N,163,170,1,5.5,0.0,0.5,2.20,0.00,0.3,11.00,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2,2021-01-15 11:50:54,2021-01-15 12:05:03,1,2.72,1,N,239,164,1,12.0,0.0,0.5,2.00,0.00,0.3,17.30,2.5
499996,1,2021-01-15 11:27:17,2021-01-15 11:43:02,0,2.40,1,N,238,237,1,11.5,2.5,0.5,2.95,0.00,0.3,17.75,2.5
499997,1,2021-01-15 11:45:13,2021-01-15 12:25:16,1,0.00,1,N,188,75,1,34.2,0.0,0.5,0.00,0.00,0.3,35.00,0.0
499998,2,2021-01-15 11:10:35,2021-01-15 11:15:56,2,0.76,1,N,238,239,1,5.5,0.0,0.5,3.00,0.00,0.3,11.80,2.5
499999,1,2021-01-15 11:15:48,2021-01-15 11:38:29,1,8.90,1,N,237,138,1,27.0,2.5,0.5,6.00,6.12,0.3,42.42,2.5

In [77]:
df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

-1

In [78]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000,
)

In [81]:
for df_chunk in df_iter:
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

In [79]:
from tqdm.auto import tqdm

In [85]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]